output_dir: '.\results'
#db_path: '/databases/102flowers'
db_path: 'F:\Downloads\102flowers\102flowers'
db_type: 'flowers'
#data_path_train: './clean_data/baby"
#data_path_test: "./clean_data/office_products"


training_args:
  batch_size: 16
  txt_max_len: 64
  learning_rate: 1e-5
  test_percent: 0.2
  val_percent: 0.2

txt2im_model_args:
  noise_dim_percent: 0.5
  generator_args:
    nf: 64
    out_dim: 224
    out_channels: 3
    kernel_size: 3
    #num_layers:
  encoder_args:
    name: 'distilbert-base-uncased'

im2txt_model_args:
  encoder_name: 'facebook/deit-base-distilled-patch16-224'
  decoder_name: 'gpt2'

