output_dir: './results'
db_path: '../databases/102flowers'
db_type: 'flowers'

training_args:
  batch_size: 4
  txt_max_len: 10
  learning_rate: 1e-5
  test_percent: 0.98
  val_percent: 0.01

txt2im_model_args:
  noise_dim_percent: 0.5
  generator_args:
    nf: 64
    out_dim: 224
    out_channels: 3
    kernel_size: 3
    #num_layers:
  linear_out_dim: 100
  encoder_args:
    name: 'distilbert-base-uncased'

im2txt_model_args:
  encoder_name: 'facebook/deit-base-distilled-patch16-224'
  #decoder_name: 'distilgpt2'
  decoder_name: 'gpt2'

